[package]
name = "cn-kip-types"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
nostr-sdk.workspace = true
serde.workspace = true
serde_json.workspace = true

cn-core = { path = "../cn-core" }
